### ISSUE TITLE
Documentation: Write README

### ISSUE THREAD

**Issue by RitaDee** [RitaDee/my-portfolio#4]
Write a proper readme for this.

**Comment by Suraj-kumar00** [comment]
Hi @RitaDee, how are you doing?
I can write the proper readme for this. Can you assign it to me and please do give me some context for the readme like these area should be cover and in this manner.

**Comment by RitaDee** [comment]
> Hi @RitaDee, how are you doing? I can write the proper readme for this. Can you assign it to me and please do give me some context for the readme like these area should be cover and in this manner.

Hi @Suraj-kumar00, I appreciate your interest. Sorry, but it is not open to contributors for now.
